services:
  postgresql:
    image: bitnami/postgresql:latest
    container_name: postgresql_turilha
    environment:
      POSTGRES_USER: turilha_user
      POSTGRES_PASSWORD: trilhinha-paulino-neves-campos
      POSTGRES_DB: turilha_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/bitnami/postgresql
    restart: unless-stopped

volumes:
  pgdata: